### ISSUE TITLE
Observation - When naming network boxes for props, if there are spaces in the name, the props will not load.

### ISSUE THREAD

**Issue by Stikyhooves** [Baldrax/Houdini_TaleSpire_Terrain_Generation_Toolset#18]
Not a real issue, just an observation of an idiosyncrasy that may be worth noting in the comments of the default terrain setup. When naming network boxes for props, if there are spaces in the name, the props will not load. This can be replicated by renaming a prop network box to have a space rather than underscore, correcting the node reference, and refreshing the biome. 

Replacing spaces in the name with underscores (as god intended for all naming conventions) resolves this issue. Took me a while to figure this out because I usually favor underscores. 

-Oz

![NamingFail_01](https://user-images.githubusercontent.com/111915077/206573739-a11824df-3af4-4ce5-8310-7b792c48e917.JPG)
![NamingFail_02](https://user-images.githubusercontent.com/111915077/206573749-5c34b9e6-e04c-4ac0-aac5-e641b5623df4.JPG)

**Comment by Baldrax** [comment]
Yes, I am aware of this but thanks for bringing it up to remind me to see if I can resolve that or at least put up a warning about it.
In the Forest_Gully example file I made a note about it (typos and all), but there is a lot of info in that file to take in and I'm not sure if everyone goes through it all.
![image](https://user-images.githubusercontent.com/100365731/206823873-330c5442-a5c0-46c0-90f8-5e64a8b78dfa.png)

I have a feeling I may be able to figure out how to get it to work with spaces, I'm not exactly sure why it doesn't, but I haven't looked at that code in a while.

**Comment by Stikyhooves** [comment]
Rgr that. I just have the base version. The only note that shows when adding a new terrain node is much lighter: 
![CurrentText](https://user-images.githubusercontent.com/111915077/206824655-92aef9a5-374a-4d85-bf7d-b367b329fc66.JPG)

**Comment by Baldrax** [comment]
Yeah, the example_Forest_Gully file has way more notes and guides you through the entire terrain process, it is worth a browse through.

That said, I found the root of the problem and a fix should go out in the next version:

There is a function to isolate the group of items to be selected on some of the Houdini nodes:
```@name==`chs("../tile_set_1x1")` ```

It needed to be protected by quotes to preserve the entire name with spaces:
```@name=="`chs("../tile_set_1x1")`" ```

It is in a few places in the Tiler and the Scatter nodes so I'll fix it, test it out then add it to the next release.

**Comment by Stikyhooves** [comment]
I'll have to dig around and find that. :) - Thanks.

**Comment by Baldrax** [comment]
It is in the directory for the toolset, under hip/examples/...
